spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingroom?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Turkey
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: Melih.oguz44
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

